name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: write 
  pages: write    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 

      - name: Vite GitHub Pages Deployer
        run:  |
            git config --global user.email "aachauhan98@gmail.com"
            git config --global user.name "Archana8360"
            npm install
            npm run deploy
